### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by pfrandsen** [letsencrypt/acme-spec#104]
I do not see any mentioning of subdomains in the spec so I wonder if the following use-case is handled (if not, I think it should be).

Lets say that I own domain intranet.net. Lets also assume that the domain is not associated with a web server that is publicly available on the internet (it is for internal use in my organization and is behind a completely closed firewall). Thus I can prove ownership of the domain by adding records to the public dns server, but I cannot provision a file on a web server to prove ownership of the domain or any subdomains (thats the important part).

Now I can execute "lets-encrypt intranet.net" to get a domain certificate for intranet.net

On my intranet I have a number of subdomains that I would like to obtain domain certificates for (app1.intranet.net, app2.intranet.net, ...) but I do not want to register these in a public dns.

Is it possible to obtain domain certificates for these subdomains based on the proven ownership of the parent domain?

* lets-encrypt app1.intranet.net (certificate issued based on proven ownership of intranet.net)
* lets-encrypt app2.intranet.net (certificate issued based on proven ownership of intranet.net)

**Comment by titanous** [comment]
#97 allows provisioning a wildcard if the FQDN to the right of the wildcard is validated, so it seems logical that validating a domain should allow you to create certs with additional labels on the left without additional validation.

**Comment by martinthomson** [comment]
I don't think that holds.  A request for `example.com` might be subject to different validation policies than a request for `*.example.com`.  They might use the same basic validation tools, or not.  The wildcard might however be subject to additional audit.

**Comment by titanous** [comment]
@martinthomson Validation and issuance are separate. The language in #97 allows issuing a wildcard for any bare domain that is validated.

**Comment by pfrandsen** [comment]
Just to make sure - it is not a wildcard certificate that I want - it is a number of individual certificates for a specific set of subdomains.

**Comment by LarsKumbier** [comment]
I'm unclear on what the advantage of your individual certificate approach is over a wildcard approach. If your goal is to hide the internal DNS names of your intranet servers, a wildcard domain will be sufficient and can be achieved by the current spec status.

Could you give an example on where a wildcard is not sufficient?

**Comment by pfrandsen** [comment]
A wildcard (of course) covers all subdomains and thereby you cannot in
practice restrict what it is used for. With individual cetificates you have
an additional level of control (and extra administration - but lets encrypt
will largely make that irrellevant ;-)

So wildcards can cover your encryption needs but they can be too broad.

**Comment by bifurcation** [comment]
This is a bad pattern to encourage.  CAs should be validating the names that they are issuing for -- authorization [does not naturally flow down the DNS hierarchy](http://datatracker.ietf.org/wg/dbound/charter/).  

That said, private names can still get certs with ACME if they are public at the time of validation, as long as the CAs policy allows this (vs. doing more continuous validation).

**Comment by pfrandsen** [comment]
I do not see why that is a bad pattern - and if it is, then CAs should not issue wildcard certificates. For a wildcard certificate ownership  of the demain is verified (you do not publish and maintain the subdomain in dns) and it is the exact same situation for subdamains - only more restrictive in terms of the certificate issued. Forcing you to use wildcards or publicly publish subdomains is a net negative for security (especially the wildcard option).

For the corpoate world it is an important usecase that is not being supported (and that is of course ok) - we will wait for DBOUND and keep doing what we do now (typically self-signed).

**Comment by ronneseth** [comment]
I run a company that host 300+ e-commerce stores corporate customers. Frequently, we are asked to setup stores on subdomains and have us fully manage that subdomain, including SSL. The owner of the TLD will point the subdomain, in my mind authorizing us to request SSL certificates for that subdomain on their behalf. In fact, in our case, the owner of the TLD really does not want to deal with this at all (the coordination overhead, manual work both for us and for the customer, etc).

What I think makes sense in these situations is that if you control the host of the subdomain, you should be able to request an SSL certificate for that subdomain. 

I definitely do not think that authorization flows up to "if you control the host of a subdomain, you can authorize a wildcard certificate" or "if you control the host of the subdomain, you can authorize a top-level domain certificate".

I had a similar experience with Zendesk as their customer -- I wanted them to host support.revolutionparts.com and I had to go through a manual process to have them secure this subdomain on my behalf. I'd much rather authorize them to request an SSL cert on my behalf and I authorize that by the A record or CNAME record I pointed to Zendesk (since I control the TLD).

**Comment by josteink** [comment]
I genuinely think this issue should be reopened.

In the scenario of wanting to issue certificates for specific hosts while and at the same time having a secondary subject (a top level DNS round robin for redundancy) is a very normal use-case.

If I can prove I own the top level domain, I should be allowed to issue certs for any subdomain without need for verification.

Without support for this, I'm forced to use StartSSL for my cert needs (as they *will* issue certificates for any subdomains of a domain I can prove ownership of).

**Comment by jsha** [comment]
Could you re-post to the acme@ietf.org list? That's where all discussion is happening now.

**Comment by josteink** [comment]
Thanks. Done.
