### ISSUE TITLE
DVSNI as specced requires labels that are too long

### ISSUE THREAD

**Issue by pde** [letsencrypt/acme-spec#107]
Since some webservers may refuse to respond to SNI names that are longer than 63 bytes, the DVSNI challenge shouldn't demand them.

**Comment by jdkasten** [comment]
The issue isn't the SNI name.  The nonce used for the SNI name is only 16 bytes hex encoded (length of 32).  The issue is with the Z value which is 32 bytes... (specified as hex encoded (64)) within the certificate.

Relevant discussion here: https://www.ietf.org/mail-archive/web/acme/current/msg00211.html
