### ISSUE TITLE
Improve revocation process

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#116]
Right now, if you have a private key and want to revoke the corresponding certificate, you submit an ACME revocation request signed by that private key. Ideally we should only ever sign ACME messages with account keys, not cert keys. We should change the flow to include some other form of proof that you control the corresponding private key.

**Comment by diafygi** [comment]
Is it possible to create a CSR with a revocation attribute? Maybe a [Invalidity Date](http://www.alvestrand.no/objectid/2.5.29.24.html)? If so, a user could submit a revoking CSR as the payload, and the whole request would still be signed by the account key.

**Comment by bifurcation** [comment]
I'm closing this because I think that we're already covered (see below).  @jsha, if you disagree, please let me know.

The spec already allows revocation when "the public key of the key pair signing the request matches the public key in the certificate".  I don't think that we need to limit ACME signatures to account keys -- the key that signs the revocation request is the authorizing key, whatever its source.
