### ISSUE TITLE
Proposal: localhost.letsencrypt.org dev certs

### ISSUE THREAD

**Issue by coolaj86** [letsencrypt/acme-spec#117]
I spend a lot of time developing on my laptop, but I'd like to have my dev and prod environments mirror each other as best as possible.

Could we get local.letsencrypt.org or localhost.letsencrypt.org to point to 127.0.0.1 and allow issuers to issue certs to 127.0.0.1 addresses without completing the loopback process?

**Comment by jcjones** [comment]
I think I would prefer we put this at `localhost.letsencrypt-demo.org`; some DNS resolvers (OpenDNS, for example) get (rightfully) suspicious of domain names that have loopback entries due to the possibility of DNS rebinding attacks.

That said @coolaj86, having such a whitelisted domain for the test environment makes sense to me, but should really be covered under [Boulder](https://github.com/letsencrypt/boulder/issues/). Would you please re-file this Issue there?

**Comment by martinthomson** [comment]
@jcjones, Is there anything preventing you from issuing certificates for a bare 'localhost' or 'localhost.localdomain' ?  I can imagine that the CAB BR might have something to say about that.  Why create new DNS entries when `/etc/hosts` already contains all that you need.

**Comment by jcjones** [comment]
@martinthomson Blacklisted domains are definitely a matter for Boulder's policy engine, which can be initialized differently by each CA using the software. The ACME protocol compatibility testing site isn't a trusted entity.

**Comment by martinthomson** [comment]
I'm not sure that I follow that response.  Are you saying that localhost is a blacklisted domain? or that this is a matter of CA policy?

**Comment by jcjones** [comment]
I would imagine localhost and anything that resolves to private address space to be restricted, and that restricted domains to be a matter of CA policy.

This request appears to be a Boulder enhancement for simplified testing; the OP wants to be able to run/write an ACME client against Boulder without extra work of `/etc/hosts` and running a DVSNI / SimpleHTTPS-capable server. Possibly without even running the Validation Engine against the request.

**Comment by martinthomson** [comment]
Indeed.  I was merely suggesting the possibility that Boulder could issue trusted certificates for localhost to all comers, without validation.  There are few (working) configurations where localhost resolves to anything other than the current machine, so the risk seems low, if not non-existent.

It would also solve the age-old issue people have with testing.  I believe that there are exceptions for `http://localhost/` in the definition of "secure contexts".  Maybe those exceptions are unnecessary.

**Comment by jsha** [comment]
I'm pretty sure the BRs disallow localhost because it doesn't end in a public suffix.
I also think this is not the right approach for localhost testing. Developers should really set up a self-signed cert and add it to their trust store. This is currently a big hassle, but I think those tools will improve.
On May 1, 2015 10:33, Martin Thomson <notifications@github.com> wrote:Indeed.  I was merely suggesting the possibility that Boulder could issue trusted certificates for localhost to all comers, without validation.  There are few (working) configurations where localhost resolves to anything other than the current machine, so the risk seems low, if not non-existent.

It would also solve the age-old issue people have with testing.  I believe that there are exceptions for http://localhost/ in the definition of "secure contexts".  Maybe those exceptions are unnecessary.

**Comment by coolaj86** [comment]
I would argue that the spec should define this a behavior that either SHOULD or MUST be implemented in a proper implementation, so I still feel it deserves place in the spec, not an implementation.

However, I'm continuing this discussion at https://github.com/letsencrypt/boulder/issues/137 as requested.
