### ISSUE TITLE
Validation Vulnerabilities

### ISSUE THREAD

**Issue by moparisthebest** [letsencrypt/acme-spec#131]
These vulnerabilities would allow an attacker who doesn't control a domain to get a certificate for that domain, and are basically due to problems with DNS.

Basically I noticed a comment here:
https://github.com/letsencrypt/boulder/issues/11#issuecomment-103897922
which says letsencrypt won't support DNS validation at the start because of vulnerabilities, but the problem is all other forms of auth (DVSNI/Simple HTTPS) also rely on the same DNS to look up the domain name to connect to, and are therefore subject to the same vulnerabilities.

The *correct* and only perfect solution to this is only allowing DNSSEC signed responses for any of the above validation tests.  This means that if a response is properly covered by DNSSEC, none of the following hacks need to be applied.  But since we don't live in a perfect world, I'll propose some things that attempt to work around the issues without DNSSEC:

1. Only allowing DNS over TCP instead of UDP would prevent a non-man-in-the-middle attacker from sending a well-timed UDP response with a fake DNS record in it.
2. A man-in-the-middle could hijack DNS queries and send back whatever responses they want, this could be at the datacenter, bandwidth provider, or even a nation-state style attacker.  Here are some crazy ideas to attempt to prevent this:

    a. Have the validator perform DNS queries from 2 different providers in 2 different geographic locations with 2 different backbones (via a secure channel between servers, ssh/vpn etc), and fail if the response is not the same.  For example a server in china and the usa would likely not have the same man-in-the-middle able to forge both responses.
    b. Have the validator perform the DNS queries from the server directly then over TOR, or maybe over TOR multiple times requesting a different exit node each time, and if the same response isn't returned each time then fail.
    c. Query different DNS providers over a secure protocol like DNSCurve or something, and fail if responses are different, OpenDNS is the only one I know of that supports this right now.

The catch with methods a-c though are they fail with a load-balanced, geographic-specific, or round-robin DNS, but then maybe fancy large setups like that don't need automatic certificates?  Or maybe instead of failing if the IP's were different, you just perform whatever test you were doing on each of the IPs and verify that it passes against all IPs.

I don't know if these implementation details should be mentioned in the ACME spec per-say, or if they should just be implementation-specific like in boulder, but I feel the vulnerabilities should be mentioned at the least if not work-around ideas.

**Comment by adamtomjack** [comment]
DNSSEC won't help.  I think there is a vulnerability here, but it probably doesn't work like you'd expect.  Controlling DNS is sufficient to exploit it, but it's not necessary.  It can also be done by controlling a domain's HTTP traffic.

Your own attempt to register a domain is not the vulnerable part, even given the use of insecure DNS and HTTP.  The problem is when somebody else tries to register your domain first.  As long as you register account keys for all your domains, you're probably safe.  If you don't, you might be at risk.  Inaction is what makes you vulnerable.  You don't have to actually use letsencrypt certs, but you do have to at least register an account key.  If any other CAs start implementing this process, you would need to register account keys with them as well!

Registering your own domain is probably safe.  Most of a registration session is encrypted, so an attacker (call her Eve) can't insert her own keys or information nor can she see anything private.  At worst, she can interfere with the verification step and make it fail, but she can't gain control of anything.  All the unencrypted step does is verify that you one of the possibly many people who can control your domain.  That Eve can also control your domain is irrelevant here.  She could intercept the request and verify for you, but what does that get her?  The verification either works and the CA trusts that you control the domain, or it doesn't and you may or may not control the domain.  Please try again.

The real problem comes when Eve can control your domain and you haven't registered an account key.  Suppose Eve can intercept either your DNS or your HTTP traffic.  Either one gives her the ability to impersonate your server.  If you haven't already done so, Eve can register her own account key by intercepting the CA's verification request.  The CA will (sadly, but correctly) believe that Eve controls your domain (because she does!), so it will accept her account key.  If you normally use a different CA, you might never realize somebody else has valid certs for your domain!

It matters if somebody else can get signed certs for your domain.  Again DNSSEC doesn't help.  Suppose that Bob tries to access your site securely and that Eve can MITM his traffic.  It won't matter if Bob uses DNSSEC to learn your server's true IP address or if tries to connect with HTTPS.  Eve might not actually control your IP address or your server, but if she can intercept Bob's packets, she can easily lie about all that.  Bob will think he's sending his password to your server when he's really sending it to Eve, but he'll still believe it's your server because he sees a valid certificate "proving" it is.  Bob might never know, even if he's wary and alert.

It might seem that a MITM attack is a pretty high bar, but it's probably not.  Often all that's needed is access to a machine on the same network as the one under attack.  A little ARP spoofing can go a long way.  Think about all the other laptops sharing your coffee shop's wireless.  How many of them have viruses and are part of a botnet?  Now, are you _sure_ that the wireless router is smart enough not to forward fake ARP packets?  Really sure?  If not, all the wireless encryption in the world won't keep your data private.  Even wired ethernet can expose you.

**Comment by bifurcation** [comment]
The upshot of this is that the document needs security considerations :)  The various challenges will have vulnerabilities to things like DNS hijacking, but we just need to document them and individual ACME CAs can decide what they will support.

**Comment by moparisthebest** [comment]
@adamtomjack DNSSEC solves the issue entirely, a bad guy can no longer start a request for a cert because hijacking DNS is useless if the acme server uses DNSSEC.

@bifurcation Yes, I agree, the security issues just need documented, there is no perfect solution without DNSSEC.  I cross-posted this over at the acme-spec mailing list and they agree:
https://www.ietf.org/mail-archive/web/acme/current/msg00426.html
