### ISSUE TITLE
Add CORS requirement

### ISSUE THREAD

**Issue by diafygi** [letsencrypt/acme-spec#151]
As requested on the mailing list, I'd like to request adding Cross-Origin-Request Support (CORS) to the spec. I'm interested in making an ACME client that is a static unhosted file (i.e. file://path/to/client.html) that uses WebCryptoAPI. Additionally, this would make using the API easier for Firefox OS apps (so they wouldn't have to request the unrestricted xhr permission).

All that's needed is to require that servers have an open header in each response ("Allow-Control-Allow-Origin: *").

**Comment by jsha** [comment]
One caveat: This opens us up an additional channel for spamming of new registrations and new authorizations. Let's Encrypt anticipates rate limiting those actions by client IP address (in addition to other factors), but an attacker who can get broad distribution of their JS can use the IPs of various browsers to create such requests. As a practical matter this is probably fine. If we get a wave of attacks from such unintentional browser clients, we can stick certain User-Agents into their own rate limiting bucket. And we need to get good at cleaning up abandoned registrations anyhow.

**Comment by bifurcation** [comment]
This was addressed by #153

**Comment by tomclegg** [comment]
CORS support involves more than just adding an `Access-Control-Allow-Origin: *` header: Preflight requests using the OPTIONS method, Access-Control-Expose-Headers headers that tell the browser which response headers should be accessible to the client, etc. I suggest either
* removing the specific recommendation to add a single header, or
* adding a phrase to the effect that ACAO is just one of several necessary behaviors, perhaps just "For example, ..."

...so it's clear the reader needs to refer to the CORS spec in order to do this effectively.

(Not sure if this should be its own issue, or just reopen this one.)

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
