### ISSUE TITLE
Simple HTTPS and renewal

### ISSUE THREAD

**Issue by martinthomson** [letsencrypt/acme-spec#26]
Step 4 in the "simpleHttps" challenge demands a self-signed certificate.  That makes this challenge unusable for certificate renewal.

I would have thought that this is still a valuable thing to use for renewal requests, but you would then need to ensure that the certificate is valid for the domain.  Given that the nonce you retrieve would be confidential (and probably time-limited), I see no reason that you can't just rely on the proof-of-possession that was attached to the original request for the certificate.

**Comment by jsha** [comment]
I think it's simpler to remove the requirement that the name must match, and accept any certificate when doing SimpleHTTPS validation. Requiring a cert with the requested identifier does a little better at proving that the requester is capable of administering a web server on port 443 vs just being able to place a file. However, DVSNI validation accomplishes the same thing, but does it better.

I see SimpleHTTPS as a lower-assurance validation method that is simpler for clients to implement, and that CAs may or may not enable by policy.

**Comment by jdkasten** [comment]
I think the confusion arises because there isn't a clear idea about what SimpleHTTPS is attempting to prove.  The current spec states
"With SimpleHTTPS validation, the client in an ACME transaction proves its control over a domain name by proving that it can provision resources on an HTTPS server that responds for that domain name."  It is clear that the bulk of the challenge attempts to accomplish this description.  However, the requirement for a valid self-signed certificate by the key pair being authorized indicates some level of control over the webserver process itself.  

As @martinthomson mentioned this makes renewal impossible.  I might also add that placing any certificate requirements in SimpleHTTPS makes implementing SimpleHTTPS on the client more difficult than DVSNI.

I agree with @jsha about SimpleHTTPS and DVSNI.  I believe SimpleHTTPS should stick with its description and drop the requirements for the certificate.

**Comment by bifurcation** [comment]
Addressed by #126
