### ISSUE TITLE
proof of control: host ssh keys?

### ISSUE THREAD

**Issue by dnozay** [letsencrypt/acme-spec#31]
Hi, would a challenge based on knowing the host ssh keys be possible ?
(or even a good idea?)

Scenario: host is configured with puppet, puppet knows/generates host ssh keys ahead of time and we want to run the client & generate certs ahead of time.

**Comment by bifurcation** [comment]
I'm not seeing a workable solution here.  Certainly the example you give would not be workable -- SSH keys are not inherently bound to domain names, so we would have to make an SSH connection to the server to validate the connection between the key and the domain name (like we do with HTTPS).  That would not work before the VMs are stood up.  For generating keys before the hosts exist, ISTM that the DNS challenge type would work better.

It might be possible to do an SSH challenge type, where the CA makes an SSH connection to the server at the domain name being authorized.  But we would need a way for the SSH server to provide a token back to the CA in the validation connection, in order to bind the validation transaction to the ACME process.  And we probably don't want to have the CA actually log in to the SSH server.  I don't know SSH well enough to know whether that's possible.

So I'm open to a solution here, and have re-titled the issue to reflect this.  But I'm moving it to Defer because we don't have a concrete proposal yet.

**Comment by mvdkleijn** [comment]
Host SSH keys can be bound to a domain name using an SSHFP dns record, which would probably  work in this scenario but I'm not sure how secure that would be. Also, you'd be using dns again..

I would suggest this should not be supported.

We use Chef ourselves and I know of the possible timing issues with spinning up new machines. However, I would suggest that since letsencrypt /ACME is supposed to be an automated setup, it should not matter what certificate you get.

Simply spin up the machine and install the automated client which runs on a restricted port not conflicting with other services. Or am I missing a scenario?

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
