### ISSUE TITLE
allow ports other than 443.

### ISSUE THREAD

**Issue by dnozay** [letsencrypt/acme-spec#33]
see also issue #19.

practical examples:

- https://proxy.example.com:8080/;

 port `8080` is commonly used but 8080 is not a privileged port.

- running multiple services on the same host
 - https://www.example.com:443/ - already used for regular website
 - https://www.example.com:8080/ - another service (e.g. proxy, jenkins, any app really...)

- SSL endpoint not being apache/nginx but the app 
 - `uwsgi`
 - `tomcat` / `jetty` / `winstone` servlet

**Comment by normanr** [comment]
btw, instead of TXT acme.port you may want to use SRV _acme._tcp as that is what SRV records are for :-)

**Comment by coderanger** [comment]
Would love to see this in the context of infrastructure automation. It would be much easier for Chef/Puppet/etc to spin up a little web server on a new port (but still <1024) rather than having to sort out what is listening on 443 already and interact with it to complete the verification. This could allow a more generic approach from automation/tooling.

**Comment by dol** [comment]
@kuba The idea with an optional DNS records sound like a good solution. As @normanr mentioned prefer SRV over TXT.

This is a very useful feature.
In this case, we could offload the DVSNI traffic to an different port.

**Comment by coolaj86** [comment]
The idea of SRV _acme._tcp  sounds great to me, but I worry it will be too complicated for the average joe, which is kinda who we're targeting with letsencrypt, isn't it? I mean, we want to lower the barrier to get more people on the encryption bus, right?

Why not just allow some other privileged port < 1024?

Here's what I see:
* **letsencrypt** is to help **average joe** get certificates
* **average joe** doesn't want his website to be taken **offline** to get a certificate
* **average joe** can't figure out **haproxy tcp forwarding** (and neither can I for that matter)
* He can probably figure out how to `sudo letsencrypt`

I definitely hear the argument for not allowing a user on a system request certs on behalf of that system... but I kinda disagree. Shared hosts generally don't allow their users to listen on random ports. Despite the history of linux being "multi-user", in practice I don't see it.

My motto is kinda "if you trust me enough to give me your credit card to have access to my system, you can trust that if you screw it up I'm gonna charge that lovely card of yours". If you're letting random untrusted users on your box, you've got... two problems... y'know?

**Comment by coolaj86** [comment]
It looks like port 4 is ripe for an RFC
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml

And 6,8,10,12,14,16,26,28,30,32,34,36,40,60.

In all seriousness, I'd say port 81 is quite a catch. 442 or 445 would have been nicer, but hey, 81 ain't bad.

I'm quite surprised how sparse it gets as you go further out, but there are definitely enough ports for use and if silly microsoft technologies that no one will ever use again can get through IANA, I'm sure something as monumental and web-worthy as LetsEncrypt can.

**Comment by Yvi71** [comment]
I would also love to see an option to use an alternative port, just for the reason not to take down a service that already works on 443.

**Comment by ac000** [comment]
To me, the argument of it's running on a root initiated port so it's good seems rather weak.

I see lots of chat here about insecure servers, well if that's the case assuming root is OK seems somewhat flawed. So I don't really see a big difference with using a port < 1024 or not.

Simply sending an email to an address at the domain seems just as good/bad to me and a lot less faffing about.

**Comment by kelunik** [comment]
Allowing other ports to remove the downtime for (re)validation is a good idea, especially if domain validation will take place on every renewal to make sure it's always the same process and not another process once a year.

I also think that restricting it to ports < 1024 is a must, at least by default, as it's secure by default then.

**Comment by DavidLutton** [comment]
Mumble seems to [support](http://wiki.mumble.info/wiki/Obtaining_a_StartCom_Murmur_Certificate) CA provided TLS Certs.
Some [Community - Let's Encrypt](https://community.letsencrypt.org/t/cipher-suite-order-apache/614) discussion and recent Mumble [release](http://wiki.mumble.info/wiki/1.2.9) on Cipher Suites Seem to be indicate compatible suites, not sure if Mumble plays well with sharing ports, SSL endpoints et al, also given that it is live group voice chat that it would reduce quality of service & increase total latency through an endpoint service. 

Mumble can be set to any port >1024, runs as reduced user on Ubuntu. 
Cannot claim ports "Server: TCP Listen on [::]:2 failed: The address is protected"

**Comment by mvdkleijn** [comment]
Apart from the whole discussion above where there are parts that make sense and parts that don't...

I think/hope everyone here can agree that:

1. Causing downtime for (re)validation is silly and just not acceptable.

2. ACME / letsencrypt is validating ownership of a domain, not the service(s) running on it so tying it to a certain port used by existing services seems inappropriate.

3. Defining a default port is a good thing.

4. Using port 443 for (re)validation while at the same time trying to get as many people to use that port (effectively that's what letsencrypt is trying to do) seems... counterproductive.

So... :+1: for using a separate, dedicated and registered port.

**Comment by ravisorg** [comment]
@mvdkleijn seems like a very sensible person. I would have to agree with everything there.

This might be a whacky idea with all sorts of unintended side effects that I haven't got enough caffeine in my bloodstream to see at the moment, but why not allow the client to specify the (re)validation port when making the request? By default (defaults are a good thing!) it could be 443, but if the client specifies an acceptable alternate port (<1024) then the validation service uses that port instead. This would solve pretty much any server configuration, as the client could always select a port not in use by other services at the time.

**Comment by jdkasten** [comment]
I am in favor of allowing the server to specify a set of ports to be used.

Of note, the CABForum Validation working group is currently attempting to enumerate a set of acceptable ports to perform DV.

**Comment by jsha** [comment]
@mvdkleijn: Note that the current spec does not require any downtime for revalidation. It is specifically designed so the your can provision a file or a DVSNI responder on your web server without taking it down.

Also, this early draft of the protocol has been replaced by the official IETF repo: https://github.com/ietf-wg-acme/acme. Let's do further discussion over there!

**Comment by kelunik** [comment]
Would have been nice if just the ownership had moved, so all issues and all history would have been retained.

@jsha Note, that it's not just providing a file, as we need a special `content-type` header, too. It would be nice to have the LE client really in a standalone mode, the current standalone mode is only suited for the first issuance. That way we don't need ACME support in every web server but can just always use it as standalone software for certificate management.

**Comment by mvdkleijn** [comment]
@ravisorg I would prefer to keep things simple. Lets just register a port with IANA for the standalone client. Allowing for choosing a set of ports is possible of course, but I would prefer a clearly defined and registered port.

@jsha I was under the impression that an automated update of the certificates would require downtime for validation. I'll reread.

I'm not a big fan of the DVSNI option personally. Seems overly complex to me.

The file option would be nice and possible (and at least simple) if not for the special header which seems unnecessary. A special header would make it more complex to set things up for the user who might not know how to set it up.

I was unaware the spec moved, especially concerning any discussion since there appears none in that repo. (0 issues)

I agree with @kelunik that the client needs a true standalone option for revalidation which would allow it to be tech neutral-ish.

For me personally, my ideal setup would have a completely standalone client manage the certificates for me and let me do the rest. I just don't like the idea of a third party app changing the configuration of my webserver. Seems just too fragile.

**Comment by jdkasten** [comment]
@mvdkleijn No, updates for the validation do not require downtime.  If you are required to change the configuration, most webservers allow you to simply reload ('graceful restart')

@mvdkleijn @kelunik Given that the validation is currently required to be on port 80, 443 you are going to need to interact with the existing webserver.  An option is currently being worked on. that might be of interest to you.  https://github.com/letsencrypt/letsencrypt/pull/757

Finishing this off or additional PRs are always welcome.  Though this discussion should be taking place at https://github.com/letsencrypt/letsencrypt

FYI, updates to certificates in the linked client modify a symlink so that configuration files don't have to change after installation.

Finally, if you do choose to modify config files, all configuration files are backed up before writing out to them.  If installation fails, it reverts the configuration changes (or you can manually tell it to rollback to the original configuration)

**Comment by coolaj86** [comment]
@jdkasten If Apache is currently using port 443, no number of graceful restarts in all the world will help the letsencrypt client, which also needs to run on port 443.

Or are you saying that updates don't run on 443?

Also, since it's in python instead of go (or even node), it's *painfully* slow. It takes whole seconds on a decent machine and something in the order of 30 seconds on a Raspberry Pi or similar.

**Comment by kelunik** [comment]
@coolaj86 There's another mode which just updates and reloads the Apache config to provide the validation payload IIRC.

**Comment by jdkasten** [comment]
@coolaj86 I think you misunderstood me.  Yes, as I mentioned, as it stands you are going to have to interact in some way with the running webserver.  Reload only avoids terminating existing connections and should not result in any downtime while serving the validation challenge.

@coolaj86 Yes, more clients should be written.  There was never meant to only be a single client.  There are many different use cases and different clients will have to be written.

**Comment by coderanger** [comment]
Interacting with the running Apache means you need to make assumptions about the Apache (or Nginx, or whatever) config structure. Using a secondary port would mean you could do this with no assumptions at all about the state of the system. Drop on a responder client, run the validation, shut it down, done. For stuff like Chef and Puppet integration this is hugely important.

**Comment by dol** [comment]
One idea to solve this problem without customizing/reloading the web server is to use iptables/PF to redirect traffic from the Let's Encrypt Validation Authority to a different internal port. On this port the acme client listens for challenge request and will perform the challenge.

```bash
iptables --table nat --append PREROUTING --protocol tcp 
               --source <iptables --table nat --append PREROUTING --protocol tcp 
               --source <Validation Authority IP address> --dport 443 \
               --jump REDIRECT --to-ports <ACME client port>> --dport 443 \
               --jump REDIRECT --to-ports <ACME client port>
```

For this to work the Validation Authority IP addresses should be known.

**Comment by kelunik** [comment]
@coderanger Exactly, we could drop all Nginx and Apache related code / support then.

It's
* easier to maintain the LE client code
* easier to actually use the client (less options is almost every time a good sign)
* doesn't need any assumptions about the config nor any changes there
* doesn't need to reload running production systems

@dol IP addresses of LE might change and be dynamic to prevent certain attacks, so that doesn't work.

**Comment by coderanger** [comment]
Even if the iptables trick did work, I would be very unhappy doing stuff like that in production :-P

**Comment by mvdkleijn** [comment]
What @coderanger described so eloquently and @kelunik nicely lists is exactly what I had in mind.

A letsencrypt client that messes with Apache's (or whatever) configuration is fine for simple use cases but for people with more complex setups or requirements, such a client would quickly break.

The ip tables trick is great from a theoretical pov but it makes my skin crawl for production. Also it'd be a definite no-go for less knowledgeable users.

**Comment by mvdkleijn** [comment]
@jdkasten So basically what you're saying is someone should write an open source ACME client that is a true standalone client doing what we specified earlier?

Wouldn't that potentially impact (user or service) security and hence usefulness of letsencrypt? One scenario that pops into my mind would be how you would explain to your users that a client written by a third party has a security issue in it. Assuming you're even aware of said client.

**Comment by kelunik** [comment]
@mvdkleijn ACME isn't limited to LE, there may be other CAs supporting it. Generally, other clients would handle security issues like any other software.

**Comment by coderanger** [comment]
@mvdkleijn Yes, having multiple client implementations is part of the idea. I'll be writing one in Ruby regardless, but it would be easier to not have to redo all the Apache/Nginx integration if possible.

**Comment by analogic** [comment]
@kelunik +1

I am curious why LE staff have choosen the more problematic way to cooperate with client systems instead of JUST getting the cert without web server dependencies. Isnt it easier to make one simple portable utility which will handle all comunication through dedicated port then messing with various systems with various webservers in various environments? When i first heard about LE I thought i would just add "/usr/sbin/le -d example.com -o /etc/ssl/example.com && killall -HUP httpd" to cron, open one port on firewall and forget about it... Well this is far from it

**Comment by My1** [comment]
talking about records, why not just allow to make the entire validation with a record, like TXT or srv or whatever where you store some value that the le client wants you to store?

**Comment by kelunik** [comment]
@My1 That's another challenge that's available, but it's not that easy to automate.

**Comment by My1** [comment]
if wen keep the challenge the same and just check whether or not it's still there it would be no problem, similar to the port setting a direct DNS challenge could be used optionally if you dont want LE to "mess" with your webserver's config, similar to webroot

**Comment by hardie** [comment]
Just a reminder that discussion of the protocol is at ietf@acme.org, since
change control moved to the IETF.

regards,

Ted

**Comment by kelunik** [comment]
Unfortunately, there's nobody active there.

**Comment by bifurcation** [comment]
What @hardie meant to say was acme@ietf.org, where there is a bunch of active discussion right now.

**Comment by bviktor** [comment]
Guys, we really don't care if the port needs to be <1024. Then make it 444, 456, 865, 1023, whatever. Just don't require us to stop the webserver for this.

**Comment by My1** [comment]
I see it the same way, since an alternate port can also be used for a different port forwarding when using LE inside a home network.
