### ISSUE TITLE
Clarify "refresh" in certificate response.

### ISSUE THREAD

**Issue by tillz** [letsencrypt/acme-spec#58]
Hi there,
In 5.4, the current version of the spec contains a 'refresh'-URI where the client can fetch a new certificate  via plain GET.
I think this is a great feature to prevent the abuse of stolen certificates/private keys, but currently it's not clear how the response should look like.
a) a PEM-encoded certificate could be send
b) a plain DER certificate could be send
c) the whole 'certificate'-Message could be send, containing a new certificate.
d) a HTTP-404/301/whatever could be sent.
e) According to the content-type, different types can be sent.
I definitely prefer c). This makes it easier for CAs (they may change the CA-Chain and/or refresh-URI if they perform changes on their infrastructure) and even the Client development (the 'certificate'-responder may be reused).

Additionally, I'm wondering what will happen if the certificate was revoked in the meanwhile.
To specify this, I'd suggest adding that the server may send the following status codes:
a) 200 (everything's ok)
b) 304 (the certificate was not changed)
c) 302/303 (the cert can be temporarily fetched from there)
d) 307/308 (the cert can be fetched from there & the refresh-uri should be set to the value)
e) 404 (like everywhere else)
g) 403/410 (if the certificate was revoked)
f) 503 (the client should retry later)

**Comment by bifurcation** [comment]
The refresh mechanism probably needs to be adjusted, so that part of this issue is moot.  But we should clarify what happens when you try to refresh a certificate that has been revoked.  ISTM that the right answer is probably "nothing different" -- the server just makes a decision based on the authorizations it has.  After all, the base cert in the refresh transaction is just being used to fill in the details of the new cert; it doesn't actually matter if it's been revoked, as long as the client is authorized to issue the new cert.

**Comment by bifurcation** [comment]
In #168, I'm proposing that the server MUST NOT renew based on an expired cert.  The reason for this is that we are allowing renewal without an account key's signature, which allows the account key to be much more tightly controlled.  (You just need it for authorization and initial issuance, which are much rarer than renewal, especially in the context of short-lived certs.)
