### ISSUE TITLE
example using openssl, curl, netcat

### ISSUE THREAD

**Issue by coolaj86** [letsencrypt/acme-spec#67]
In relation to https://github.com/letsencrypt/acme-spec/issues/66

It is feasible to get an demo client working with commandline tools?

I think it would be easier for me (and the general programming community) to grok. The node code I've been looking at is way more intricate than I would have expected. It's also really slow and even buggy on the newest versions (not sure whether the bugs are in the code, node, or due to incompatible API changes).

In any case knowing how this is corresponding to openssl commands would really help me out with the debugging (assuming that there even is a 1:1 mapping).

**Comment by schoen** [comment]
The node client and server are both now substantially unmaintained, as far as I know. The current active development efforts by Let's Encrypt project members are Boulder (the server, written in Go)

https://github.com/letsencrypt/boulder

and lets-encrypt (the client, written in Python)

https://github.com/letsencrypt/lets-encrypt-preview

Because of protocol changes, Boulder and the Python client currently don't interoperate, and the client development is proceeding with the (generally unmaintained) node-acme server. Hopefully that will switch over soon.

**Comment by schoen** [comment]
For the time being, the lets-encrypt-preview client should interoperate correctly with the node version (at least, we've gotten it to do so every day in testing and development purposes). If you encounter a bug there, you could file an issue in lets-encrypt-preview and we should be able to address it promptly, at least if it's not highly OS-dependent.

**Comment by bifurcation** [comment]
Given that ACME requires JWS signing of requests (for which I don't know of any good client-side tools), I don't think this is practical.

**Comment by coolaj86** [comment]
Maybe some diagrams then? Something like these: https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2?

**Comment by Soullivaneuh** [comment]
Have some bash examples with a basic and complete auth process would be a very great addition.
