### ISSUE TITLE
Poorly defined "validated" and "status" challenge fields

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#71]
https://github.com/letsencrypt/acme-spec/blob/master/draft-barnes-acme.md#authorization-resources gives an example involving "validated". It's not described (narratively) or even referenced anywhere else in the spec. What is the semantics? Can the field be omitted? Do we even need it?

Same for "status".

**Comment by kuba** [comment]
"uri" field is also not clearly described in the narrative description and missing in the aforementioned example

**Comment by jsha** [comment]
@bifurcation Can you clarify whether the authorization resource's challenge fields need the 'status', 'validated', and 'uri' fields?

**Comment by bifurcation** [comment]
I still think that all three are useful.  The "uri" field is obviously necessary -- it's how you respond to the challenge!  The "status" is helpful for transparency, so that the observer knows how the server validated authorization.  The "validated" field I could go either way on, but it seems like useful record-keeping.  I will take a look at the text and make sure it's consistent.

**Comment by bifurcation** [comment]
These fields are all defined in the challenges section, and there is a forward reference from the definition of the "challenges" field.
