### ISSUE TITLE
JWS: protected or unprotected header?

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#87]
Is there any recommendation the spec should provide on that matter?

**Comment by jsha** [comment]
The JWS draft indicates that if the header only includes a pubkey, and that key is being verified against a stored one, you don't need to protect the header. Somewhere in this doc, can't find it at the moment: https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41

The current test implementations appear to use an unprotected header, so I'd say document that.

**Comment by jsha** [comment]
> These Header Parameters MUST
   be integrity protected if the information that they convey is to be
   utilized in a trust decision; however, if the only information used
   in the trust decision is a key, these parameters need not be
   integrity protected, since changing them in a way that causes a
   different key to be used will cause the validation to fail.

**Comment by bifurcation** [comment]
Precisely, @jsha.  The only thing ACME uses for a trust decision in the JWS header is the signing key, so there's no need to protect it.  The nonce must be in the protected header to prevent replay, but there's already requirements for that.
