### ISSUE TITLE
Link header: required or optional?

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#93]
Are Link headers, "next" and "up", required? Please compare the following quotes from the spec:

"ACME uses the "next" link relation to indicate URI to contact for the next step in processing: From registration to authorization, and from authorization to certificate issuance. In this way, a **client need only be configured with the registration URI.**"

vs.

- "The server **may** also indicate its new-authorization URI using the "next" link relation."
- "(...) it **may** indicate the URI where such terms can be accessed in a Link header with link relation "terms-of-service"
- "For example, the server **can include** a Link relation header field {{RFC5988}} with relation "up" to provide a certificate under which this certificate was issued."

For the last one, if "up" Link is not provided, how otherwise would a client get a certificate chain?

**Comment by jdkasten** [comment]
Certificate-chains aren't required/necessary in a few situations.  I think keeping it as optional within the spec is reasonable.

Certainly, Let's Encrypt/Commerical-CAs will be shipping certificate chains, but other ACME applications might not need/require chains.

**Comment by kuba** [comment]
Yup, I can agree that "up" Link from /cert response should be optional.

**Comment by kuba** [comment]
I would have probably said that "terms-of-service" link MUST be present whenever service is covered by any TOS (absence of the link => no TOS at all)... But while this is probably what is necessary for Let's Encrypt (as required by its policy documents), it might not necessarily be true for other applications of the protocol.

**Comment by jsha** [comment]
I'd argue that "up" should be required, mainly because it is required for our main design use case to work correctly. Designing the client and server around optional "up" is likely to lead to a client leaving out a required intermediate. That can cause performance problems (if the client fetches the intermediate) or reliability problems (if some clients don't fetch the intermediate).

For enterprise environments where an internal ACME server is signing directly off a root, with no intermediates, the "up" link can point to a copy of the self-signed root. A client that wants to be enterprise-aware could add code to leave any self-signed certs out of the chain it configures.

For greatest generality we would specify that each resource pointed to by a cert's "up" link would also provide an "up" link, all the way to the root. The root's "up" link would be itself. But I think in the spirit of something simple that works, we don't necessarily need to specify that now.

**Comment by martinthomson** [comment]
"up" or "prev" ?

**Comment by bifurcation** [comment]
"up".  The "next" / "prev" axis has been used for motion along this issuance process; we need to use the "up" / "down" axis for the cert chain.
